/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Article;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-12-29T01:08:36.558Z[GMT]")
public interface ArticleApi {

    @Operation(summary = "", description = "", tags={ "Article" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Page of Articles", content = @Content(array = @ArraySchema(schema = @Schema(implementation = Article.class)))) })
    @RequestMapping(value = "/article",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Article>> articleGet();


    @Operation(summary = "", description = "", tags={ "Article" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Article Created") })
    @RequestMapping(value = "/article",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> articlePost(@Parameter(in = ParameterIn.DEFAULT, description = "", schema=@Schema()) @Valid @RequestBody Article body);

}

